[workspace]
resolver = "2"
members = [
    "clients/rust",
    "program",
]

[workspace.metadata.scripts.rustfmt.toolchain]
channel = "stable"

[workspace.metadata.scripts.clippy.toolchain]
channel = "stable"
