[workspace]
resolver = "2"
members = ["program"]

[workspace.metadata.scripts.rustfmt.toolchain]
channel = "nightly-2023-10-05"

[workspace.metadata.scripts.clippy.toolchain]
channel = "nightly-2023-10-05"
