name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18
  SOLANA_VERSION: 1.18.12

jobs:
  build_programs:
    name: Build programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-programs
          protoc: true
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}

      - name: Build programs
        run: pnpm programs:build --features bpf-entrypoint

      - name: Upload program builds
        uses: actions/upload-artifact@v4
        with:
          name: program-builds
          path: ./target/deploy/*.so
          if-no-files-found: error

      - name: Save all builds for clients
        uses: actions/cache/save@v4
        with:
          path: ./**/*.so
          key: ${{ runner.os }}-builds-${{ github.sha }}

  test_programs:
    name: Test programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-programs
          protoc: true
          node: ${{ env.NODE_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}

      - name: Test programs
        run: pnpm programs:test --features bpf-entrypoint
